# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yarnaid/fl/deals/fp_growth_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yarnaid/fl/deals/fp_growth_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.1.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(CMAKE_COMMAND) -E cmake_progress_start /Users/yarnaid/fl/deals/fp_growth_test/CMakeFiles /Users/yarnaid/fl/deals/fp_growth_test/FP-growth/CMakeFiles/progress.marks
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f CMakeFiles/Makefile2 FP-growth/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yarnaid/fl/deals/fp_growth_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f CMakeFiles/Makefile2 FP-growth/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f CMakeFiles/Makefile2 FP-growth/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f CMakeFiles/Makefile2 FP-growth/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
FP-growth/CMakeFiles/fp_growth.dir/rule:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f CMakeFiles/Makefile2 FP-growth/CMakeFiles/fp_growth.dir/rule
.PHONY : FP-growth/CMakeFiles/fp_growth.dir/rule

# Convenience name for target.
fp_growth: FP-growth/CMakeFiles/fp_growth.dir/rule
.PHONY : fp_growth

# fast build rule for target.
fp_growth/fast:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f FP-growth/CMakeFiles/fp_growth.dir/build.make FP-growth/CMakeFiles/fp_growth.dir/build
.PHONY : fp_growth/fast

fptree.o: fptree.cpp.o
.PHONY : fptree.o

# target to build an object file
fptree.cpp.o:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f FP-growth/CMakeFiles/fp_growth.dir/build.make FP-growth/CMakeFiles/fp_growth.dir/fptree.cpp.o
.PHONY : fptree.cpp.o

fptree.i: fptree.cpp.i
.PHONY : fptree.i

# target to preprocess a source file
fptree.cpp.i:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f FP-growth/CMakeFiles/fp_growth.dir/build.make FP-growth/CMakeFiles/fp_growth.dir/fptree.cpp.i
.PHONY : fptree.cpp.i

fptree.s: fptree.cpp.s
.PHONY : fptree.s

# target to generate assembly for a file
fptree.cpp.s:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(MAKE) -f FP-growth/CMakeFiles/fp_growth.dir/build.make FP-growth/CMakeFiles/fp_growth.dir/fptree.cpp.s
.PHONY : fptree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fp_growth"
	@echo "... fptree.o"
	@echo "... fptree.i"
	@echo "... fptree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/yarnaid/fl/deals/fp_growth_test && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

